---
ID: "6fe15b11-7273-4af6-baff-891e9bfeabca"
Parent: "75cc5ce4-8979-4008-9d3c-806477d57619"
Template: "93227c5d-4fef-474d-94c0-f252ec8e8219"
Path: /sitecore/layout/Layouts/Project
DB: master
SharedFields:
- ID: "06d5295c-ed2f-4a54-9bf2-26228d113318"
  Hint: __Icon
  Value: applications/32x32/folder_window.png
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20170212T142655Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
