---
ID: "deded6aa-3541-4ebe-89c1-85fea627acb4"
Parent: "462bb765-f578-4d46-a47b-20d16a1bfd94"
Template: "462bb765-f578-4d46-a47b-20d16a1bfd94"
Path: /sitecore/templates/Project/Common/Content Types/Hero/__Standard Values
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20170212T172107Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "ff751fcf-e0f0-488c-8662-170500da7b76"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\unicorn
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20200923T122215Z
